//##############################################################################
//##############################################################################
//
// DO NOT MODIFY THIS FILE !!!
// This file is generated by the release_setup script.
// Make changes to aux_intc.h.template or to release_setup.
//
//##############################################################################
//##############################################################################

/******************************************************************************
*
* (c) Copyright 1996-2002, Palmchip Corporation
*
* This document is an unpublished work protected under the copyright laws
* of the United States containing the confidential, proprietary and trade
* secret information of Palmchip Corporation. This document may not be
* copied or reproduced in any form whatsoever without the express written
* permission of Palmchip Corporation.
*
*******************************************************************************
*
*  File Name: aux_intc.h
*     Author: Linda Yang
*
*******************************************************************************
*
* Revision History:
*
*      Date    Name  Comments
*    --------  ---   ------------------------------------
*    03/25/02  LYT   Created.
*
*
*******************************************************************************/
/* FILE_DESC ******************************************************************/
//
// Purpose:
//    The file contains all the interrupt controller definitions for auxilliary
//    blocks.
//
// Sp. Notes:
//    The contents of this file are automatically modified by the script
//    release_setup.
//
/******************************************************************************/

#ifndef AUX_INTC_H
#define AUX_INTC_H

/*=====================*
 *  Include Files      *
 *=====================*/


/*=====================*
 *  Defines            *
 *=====================*/
 
#define INTC_DESHW_DMA_INT			INTC_DMA_AUX0_INT              
#define deshwDmaInt			dmaAux0Int

#define INTC_PCMCIA_DMA_INT			INTC_DMA_AUX1_INT              
#define pcmciaDmaInt			dmaAux1Int



#define INTC_DESHW_INT			INTC_AUX0_INT              
#define deshwInt				aux0Int

#define INTC_PCMCIA_INT			INTC_AUX1_INT              
#define pcmciaInt				aux1Int

#define INTC_IDE3710_INT			INTC_AUX2_INT              
#define ide3710Int				aux2Int

#define INTC_ENET_INT			INTC_AUX3_INT              
#define enetInt				aux3Int

#define INTC_ENET1_INT			INTC_AUX4_INT              
#define enet1Int				aux4Int

#define INTC_IDE37101_INT			INTC_AUX5_INT              
#define ide37101Int				aux5Int

#define INTC_ATA_INT			INTC_AUX6_INT              
#define ataInt				aux6Int




#endif /* AUX_INTC_H */
