//##############################################################################
//##############################################################################
//
// DO NOT MODIFY THIS FILE !!!
// This file is generated by the release_setup script.
// Make changes to aux_reg_map.h.template or to release_setup.
//
//##############################################################################
//##############################################################################

/******************************************************************************
*
* (c) Copyright 1996-200, Palmchip Corporation
*
* This document is an unpublished work protected under the copyright laws
* of the United States containing the confidential, proprietary and trade
* secret information of Palmchip Corporation. This document may not be
* copied or reproduced in any form whatsoever without the express written
* permission of Palmchip Corporation.
*
*******************************************************************************
*
*  File Name: aux_reg_map.h
*     Author: Linda Yang 
*
*    Purpose: Contains the chip register definitions for auxilliary blocks of
*             the PalmPak system.
*
*  Sp. Notes: The contents of this file are automatically modified by the
*             script release_setup.
*
*
*******************************************************************************
*
* Revision History:
*
*      Date    Name  Comments
*    --------  ---   ------------------------------------
*    03/25/02  LYT   Created
*
*
*******************************************************************************/

#ifndef AUX_REG_MAP_H
#define AUX_REG_MAP_H

/*=====================*
 *  Include Files      *
 *=====================*/


/*=====================*
 *  Defines            *
 *=====================*/

#define DESHW		AUX0
#define PCMCIA		AUX1
#define IDE3710		AUX2
#define ENET		AUX3
#define ENET1		AUX4
#define IDE37101		AUX5
#define ATA		AUX6


#define DESHW_BASE		AUX0_BASE
#define PCMCIA_BASE		AUX1_BASE
#define IDE3710_BASE		AUX2_BASE
#define ENET_BASE		AUX3_BASE
#define ENET1_BASE		AUX4_BASE
#define IDE37101_BASE		AUX5_BASE
#define ATA_BASE		AUX6_BASE



/* The following are automatically defined for all aux blocks by running the
** software release_setup script.  The presence of the define does not 
** necessarily mean that the block is capable of using DMA.
*/
#define DMA_DESHW_BASE		DMA_AUX0_BASE
#define DMA_PCMCIA_BASE		DMA_AUX1_BASE



/* The following are hard coded and will not be updated by the software
** release_setup script.
*/
#define DMA_ATA_BASE                    (DMA_AUX1_BASE)




#endif /* AUX_REG_MAP_H */

